var SESSION_ID_CELL="B2";
var USERNAME_CELL="B5";
var USER_ID_CELL="B1";
var TIME_ZONE_CELL="B3";
var ENABLED_CELL="B4";
var LAST_UPDATED_CELL="B6";
var RECORD_COUNT_CELL="B7";
var PYRAMID_PATTERN_CELL="B8";
var PYRAMIDS_DETECTED_CELL="B9";

var PELOTON_PLATFORM="web";
var PELOTON_API_BASE="https://api.onepeloton.com";
var WORKOUTS_SHEET_NAME="Workouts";
var CONFIG_SHEET_NAME="Config";